### ISSUE TITLE
wrap generated HTML

### ISSUE THREAD

**Issue by elizabethyalkut** [sdobreff/footnotes#11]
How can I manipulate the HTML of the footnotes? I'd like to wrap the generated footnote ol in a block wrapper in my theme, but I don't see a template I can override.

**Comment by sdobreff** [comment]
Sorry - i ve missed your post.
The footnotes are in 3 blocks:
**.awesome-footnotes-header** class  - before the footnotes
**.footnotes** - the footnotes block
and 
**.awesome-footnotes-footer** - post footnotes block

or the footnotes are in, like you mentioned ol with class footntes

there is no separate template used for that, probably that is not a bad idea.

Anyway - there are 2 hooks - _awef_footnotes_header_ and _awef_footnotes_footer_, you can use them in your them code like this:


```
\add_action(
	'awef_footnotes_header',
	function ( $footnotes ) {
		return $footnotes . '<div class="main">';
	}
);

\add_action(
	'awef_footnotes_footer',
	function ( $footnotes ) {
		return $footnotes . '</div>';
	}
);
```

And that will create a **div** wrapper with class "_main_"

**Comment by sdobreff** [comment]
As of v3.7 there is a template file (which you can overwrite in your theme if you need to) in templates/footnotes.php

If you want to overwrite it in your theme - the plugin will search within the awesome-footnotes sub-dir for file footnotes.php to use as a template.
