### ISSUE TITLE
Footnotes CSS declarations appear in post/page

### ISSUE THREAD

**Issue by elizabethyalkut** [sdobreff/footnotes#14]
I think there's something malformed in https://github.com/sdobreff/footnotes/blob/a83e47d9d6e24cfa9931982c14c33b70d836d902/templates/footnotes.php#L12 -- the default and my custom CSS declarations styling my footnotes show in the saved post, screenshot below:
<img width="1312" alt="Screenshot 2024-11-14 at 3 03 02 PM" src="https://github.com/user-attachments/assets/9cee0729-4e03-4f7c-a5b3-0fe431571f7c">

**Comment by sdobreff** [comment]
Unfortunately can't tell you what is wrong with the given context. If you put <style> tags in the custom css - remove it please - those are added automatically.
If you can export the settings and send it, that could give more info about the problem, also - is there a page where i can see this - staging site ?

**Comment by sdobreff** [comment]
Well i afraid that there is nothing much that can be done from the plugin side as it looks like some of your plugins or theme (or even custom code)  i am not sure what, is stripping out the <style> tags the plugin tries to add to the content (or at least i guess that this is whats happening).
The possible solution is to create your own template in the theme directory. Or:
in your theme dir create a sub-dir called "awesome-footnotes", and copy and paste the file you mentioned in your first comment - [footnotes/templates/footnotes.php](https://github.com/sdobreff/footnotes/blob/a83e47d9d6e24cfa9931982c14c33b70d836d902/templates/footnotes.php#L12) there,
then open that file, and remove line 12 all along.
Then add your custom css code adjustments in the css file you are using (global one).
